# syntax = docker/dockerfile:1.4
# vim: syntax=dockerfile

ARG DNF_OPTS="\
  --nobest \
  --nodocs \
  --setopt=install_weak_deps=0 \
  --setopt=keepcache=1 \
  --setopt=cachedir=/var/cache/dnf \
  "
ARG ACCEL_CONFIG_SRC="/accel-config"

FROM quay.io/rockylinux/rockylinux:10 AS build

ARG SPDK_CEPH_VERSION \
    CEPH_CLUSTER_CEPH_REPO_BASEURL \
    SPDK_VERSION \
    DNF_OPTS \
    SPDK_PKGDEP_ARGS \
    SPDK_CONFIGURE_ARGS \
    SPDK_TARGET_ARCH \
    SPDK_MAKEFLAGS \
    ACCEL_CONFIG_SRC

RUN <<EOF
    echo Log variables
    echo ======================================================================
    echo SPDK_PKGDEP_ARGS=$SPDK_PKGDEP_ARGS
    echo SPDK_CONFIGURE_ARGS=$SPDK_CONFIGURE_ARGS
    echo SPDK_TARGET_ARCH=$SPDK_TARGET_ARCH
    echo SPDK_MAKEFLAGS=$SPDK_MAKEFLAGS
    echo CEPH_CLUSTER_CEPH_REPO_BASEURL=$CEPH_CLUSTER_CEPH_REPO_BASEURL
    echo ACCEL_CONFIG_SRC=$ACCEL_CONFIG_SRC
    echo ======================================================================
EOF

WORKDIR /src
COPY . .

COPY <<EOF /etc/yum.conf
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=True
best=False
skip_if_unavailable=False
cachedir=/var/cache/dnf
install_weak_deps=0
keepcache=True
tsflags=nodocs
EOF

ARG SPDK_CEPH_VERSION=19.2.3
ARG CEPH_CLUSTER_CEPH_REPO_BASEURL=https://download.ceph.com/rpm-${SPDK_CEPH_VERSION}/el10/\$basearch

COPY <<EOF /etc/yum.repos.d/ceph.repo
[Ceph]
name=Ceph packages for \$basearch
baseurl=${CEPH_CLUSTER_CEPH_REPO_BASEURL}
enabled=1
priority=2
gpgcheck=0

[Ceph-noarch]
name=Ceph noarch packages
baseurl=https://download.ceph.com/rpm-${SPDK_CEPH_VERSION}/el10/noarch
enabled=1
priority=2
gpgcheck=0
EOF


COPY spdk/ /src/
COPY spdk/scripts/ /src/scripts/
COPY spdk/rpmbuild/ /src/rpmbuild/
RUN ls -l /src/rpmbuild/
RUN ls -l /src/configure && ls -l /src/rpmbuild/rpm.sh

RUN \
    --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    --mount=type=cache,target=/root/.cache/pip \
    # rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org \
    # && rpm --import https://www.elrepo.org/RPM-GPG-KEY-v2-elrepo.org \
    dnf install -y $DNF_OPTS -y 'dnf-command(config-manager)' \
    # && yum install -y https://www.elrepo.org/elrepo-release-10.el10.elrepo.noarch.rpm \
    && dnf config-manager --set-enabled crb \
    && dnf install $DNF_OPTS -y \
        rpm-build \
        git-core \
	&& dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm \
    && scripts/pkgdep.sh $SPDK_PKGDEP_ARGS \
    && dnf $DNF_OPTS update -y

RUN \
    --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    --mount=type=cache,target=/root/.cache/pip \
    dnf groupinstall -y "Development Tools" \
    && dnf install -y autoconf automake libtool pkgconf rpm-build rpmdevtools \
    && dnf install -y which asciidoc xmlto libuuid-devel json-c-devel zlib-devel openssl-devel \
    && mkdir -p $ACCEL_CONFIG_SRC \
    && git clone https://github.com/intel/idxd-config.git $ACCEL_CONFIG_SRC \
    && pushd $ACCEL_CONFIG_SRC \
    && ./autogen.sh \
    && ./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc \
                   --libdir=/usr/lib64 --enable-test=yes \
                   --disable-docs \
    && mkdir -p /root/rpmbuild/SOURCES \
    && make rhel/accfg.spec \
    && ./rpmbuild.sh \
    && ls -l /root/rpmbuild/RPMS/$(uname -m) \
    && rpm -ivh /root/rpmbuild/RPMS/$(uname -m)/accel-config-"*".rpm \
    && ls -l /usr/include/accel-config/libaccel_config.h

RUN \
    --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    DEPS="no" \
    SPDK_VERSION=${SPDK_VERSION:?} \
    RPM_RELEASE=0 \
    MAKEFLAGS=$SPDK_MAKEFLAGS \
    rpmbuild/rpm.sh $SPDK_CONFIGURE_ARGS --target-arch="${SPDK_TARGET_ARCH:?}"

# build bdevperf example, will not be a part of generated rpm
RUN make -C ./examples/bdev/bdevperf

#------------------------------------------------------------------------------
FROM registry.redhat.io/ubi10/ubi:latest AS rpm-export
COPY --from=build /root/rpmbuild/rpm /rpm
COPY --from=build /root/rpmbuild/RPMS /rpm

#------------------------------------------------------------------------------
FROM registry.redhat.io/ubi10/ubi:latest as spdk

ARG SPDK_CEPH_VERSION \
    SPDK_VERSION \
    DNF_OPTS

ARG SPDK_ROCKY_BASE="https://dl.rockylinux.org/pub/rocky/10/BaseOS/x86_64/os/Packages/r/"
# This would become obsolete as the release rolls out new packages
ARG SPDK_ROCKY_REPO_VER="10.1-1.5.el10"

ARG SPDK_PKGDEP_ARGS \
    SPDK_CONFIGURE_ARGS \
    SPDK_TARGET_ARCH \
    SPDK_MAKEFLAGS

ARG SPDK_NAME \
    SPDK_SUMMARY \
    SPDK_DESCRIPTION \
    SPDK_URL \
    SPDK_MAINTAINER \
    BUILD_DATE \
    SPDK_GIT_REPO \
    SPDK_GIT_BRANCH \
    SPDK_GIT_COMMIT

# Generic labels
LABEL name="$SPDK_NAME" \
      version="$SPDK_VERSION" \
      summary="$SPDK_SUMMARY" \
      description="$SPDK_DESCRIPTION" \
      maintainer="$SPDK_MAINTAINER" \
      release="" \
      url="$SPDK_URL" \
      build-date="$BUILD_DATE" \
      vcs-ref="$SPDK_GIT_COMMIT"

# SPDK-specific labels
LABEL io.spdk.version="$SPDK_VERSION" \
      io.spdk.build.pkgdep-args="$SPDK_PKGDEP_ARGS" \
      io.spdk.build.configure-args="$SPDK_CONFIGURE_ARGS" \
      io.spdk.build.makeflags="$SPDK_MAKEFLAGS" \
      io.spdk.build.target-arch="$SPDK_TARGET_ARCH" \
      io.spdk.build.ceph-release="$SPDK_CEPH_VERSION" \
      io.spdk.git.repo="$SPDK_GIT_REPO" \
      io.spdk.git.branch="$SPDK_GIT_BRANCH" \
      io.spdk.git.commit="$SPDK_GIT_COMMIT"

# Rocky Linux-specific labels
LABEL org.rockylinux.url="$SPDK_ROCKY_BASE" \
      org.rockylinux.version="$SPDK_ROCKY_REPO_VER"

COPY --from=build /etc/yum.conf /etc/yum.conf
COPY --from=build /etc/yum.repos.d/ceph.repo /etc/yum.repos.d/ceph.repo

RUN \
    --mount=type=bind,from=build,source=/root/rpmbuild/rpm,target=/rpm \
    --mount=type=bind,from=build,source=/root/rpmbuild/RPMS,target=/accel-rpms \
    --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    --mount=type=secret,id=org-id \
    --mount=type=secret,id=activation-key \
    set -euxo pipefail \
    \
    # Register RHEL
    && subscription-manager register \
        --activationkey=$(cat /run/secrets/activation-key) \
        --org=$(cat /run/secrets/org-id) \
    \
    && subscription-manager repos \
        --enable=rhel-10-for-x86_64-baseos-rpms \
        --enable=rhel-10-for-x86_64-appstream-rpms \
        --enable=codeready-builder-for-rhel-10-x86_64-rpms \
    \
    # Debug visibility
    && echo "==== SPDK RPMs ====" \
    && ls -l /rpm/$(uname -m) \
    && echo "==== ACCEL RPMs ====" \
    && ls -l /accel-rpms/$(uname -m) \
    \
    # Base dependencies
    && dnf install -y \
        dnf-plugins-core \
        libnbd \
        libaio \
        numactl \
        libuuid \
        json-c \
        zlib \
        openssl \
        rdma-core \
        pkgconf-pkg-config \
        --setopt=install_weak_deps=0 \
    \
    # Install ONLY required accel-config RPMs (NO debuginfo!)
    && dnf install -y \
        /accel-rpms/$(uname -m)/accel-config-libs-*.rpm \
        /accel-rpms/$(uname -m)/accel-config-[0-9]*.rpm \
        --exclude="*debuginfo*" \
        --exclude="*debugsource*" \
        --nogpgcheck \
        --setopt=install_weak_deps=0 \
    \
    # Install SPDK
    && dnf install -y \
        /rpm/$(uname -m)/*.rpm \
        --nogpgcheck \
        --setopt=install_weak_deps=0 \
        --allowerasing \
        --best \
    \
    # Verify
    && rpm -qa | grep -i spdk \
    \
    # Final cleanup/update
    && dnf update -y --exclude=openssl-fips-provider \
    \
    && subscription-manager unregister \
    && subscription-manager clean \
    && dnf clean all

ENTRYPOINT [ "/usr/local/bin/nvmf_tgt" ]
CMD [ "-u", "-r", "/var/tmp/spdk.sock" ]

#------------------------------------------------------------------------------
FROM spdk AS bdevperf

# Default test run duration in secs
ENV BDEVPERF_TEST_DURATION="90"

# RPC socket path
ENV BDEVPERF_SOCKET="/tmp/bdevperf.sock"

# IO Queue depth
ENV BDEVPERF_IO_QUEUE="128"

# IO Block size
ENV BDEVPERF_IO_BS="4096"

# Type of I/O pattern, see https://spdk.io/doc/bdevperf.html
# for available types
ENV BDEVPERF_IO_TYPE="verify"

# Core list
ENV BDEVPERF_CORE_LIST="0"

COPY --from=build /src/build/examples/bdevperf /usr/local/bin/bdevperf
COPY --from=build /src/examples/bdev/bdevperf/bdevperf.py /usr/libexec/spdk/scripts/bdevperf.py
RUN echo "#!/bin/sh -x"                                                 > /entrypoint
RUN echo "bdevperf -z -r \$BDEVPERF_SOCKET \\"                         >> /entrypoint
RUN echo "         --lcores \$BDEVPERF_CORE_LIST \\"                   >> /entrypoint
RUN echo "         -q \$BDEVPERF_IO_QUEUE -o \$BDEVPERF_IO_BS \\"      >> /entrypoint
RUN echo "         -w \$BDEVPERF_IO_TYPE -t \$BDEVPERF_TEST_DURATION"  >> /entrypoint
RUN chmod 755 /entrypoint

ENTRYPOINT [ "/entrypoint" ]