# syntax = docker/dockerfile:1.4

ARG DNF_OPTS="\
  --nobest \
  --nodocs \
  --setopt=install_weak_deps=0 \
  --setopt=keepcache=1 \
  --setopt=cachedir=/var/cache/dnf \
"

ARG ACCEL_CONFIG_SRC="/accel-config"

#------------------------------------------------------------------------------

FROM registry.redhat.io/ubi10/ubi:latest AS build

ARG SPDK_VERSION \
    SPDK_CEPH_VERSION \
    SPDK_PKGDEP_ARGS \
    SPDK_CONFIGURE_ARGS \
    SPDK_TARGET_ARCH \
    SPDK_MAKEFLAGS \
    DNF_OPTS \
    ACCEL_CONFIG_SRC

WORKDIR /src
COPY . .

COPY ceph.repo /etc/yum.repos.d/ceph.repo
COPY ceph-pkgset /tmp/ceph-pkgset

COPY spdk/ /src/
COPY spdk/scripts/ /src/scripts/
COPY spdk/rpmbuild/ /src/rpmbuild/
RUN ls -l /src/rpmbuild/
RUN ls -l /src/configure && ls -l /src/rpmbuild/rpm.sh

RUN --mount=type=secret,id=org-id \
    --mount=type=secret,id=activation-key \
    set -eux \
    && subscription-manager register \
        --activationkey=$(cat /run/secrets/activation-key) \
        --org=$(cat /run/secrets/org-id) \
    && subscription-manager repos \
        --enable=rhel-10-for-x86_64-baseos-rpms \
        --enable=rhel-10-for-x86_64-appstream-rpms \
        --enable=codeready-builder-for-rhel-10-x86_64-rpms

# Install build dependencies
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    dnf install -y $DNF_OPTS \
        rpm-build git-core \
        dnf-plugins-core \
    && dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm \
    && dnf groupinstall -y "Development Tools" || true \
    && dnf install -y \
        autoconf automake libtool pkgconf rpmdevtools \
        which asciidoc xmlto \
        libuuid-devel json-c-devel zlib-devel openssl-devel

# Build accel-config
RUN git clone https://github.com/intel/idxd-config.git $ACCEL_CONFIG_SRC \
    && cd $ACCEL_CONFIG_SRC \
    && ./autogen.sh \
    && ./configure --prefix=/usr --libdir=/usr/lib64 \
    \
    && rpmdev-setuptree \
    \
    && make rhel/accfg.spec \
    && ./rpmbuild.sh

# Install accel locally (safe)
RUN rpm -ivh /root/rpmbuild/RPMS/$(uname -m)/accel-config*.rpm

# Build SPDK RPMs
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    set -euxo pipefail \
    \
    && dnf install -y \
        gcc gcc-c++ make cmake \
        glibc-devel \
        \
        rpm-build rpmdevtools \
        git-core \
        dnf-plugins-core \
        pkgconf-pkg-config \
        autoconf automake libtool \
        which \
        \
        asciidoc xmlto \
        \
        libuuid-devel json-c-devel zlib-devel openssl-devel libaio-devel \
        \
        numactl numactl-devel \
        \
        libpcap libpcap-devel \
        libbsd-devel \
        jansson-devel \
        libarchive-devel \
        \
        procps-ng \
        \
        meson ninja-build \
        python3 python3-devel python3-pip python3-pyelftools \
        \
        librados-devel librbd-devel \
        \
        fuse3 fuse3-devel \
        \
        nasm isa-l-devel \
        \
        ncurses ncurses-devel readline-devel \
        \
        # DPDK build stability
        libfdt-devel elfutils-libelf-devel \
        \
        --setopt=install_weak_deps=0 \
    \
    && export PATH=/usr/bin:/usr/local/bin:$PATH \
    \
    # Build SPDK RPM
    && DEPS="no" \
       SPDK_VERSION=${SPDK_VERSION} \
       MAKEFLAGS=$SPDK_MAKEFLAGS \
       rpmbuild/rpm.sh $SPDK_CONFIGURE_ARGS --target-arch="${SPDK_TARGET_ARCH}"

# Build bdevperf binary
RUN make -C ./examples/bdev/bdevperf

#------------------------------------------------------------------------------
FROM registry.redhat.io/rhel10/rhel:10.0 AS spdk

ARG DNF_OPTS

COPY ceph.repo /etc/yum.repos.d/ceph.repo

RUN \
    --mount=type=secret,id=org-id \
    --mount=type=secret,id=activation-key \
    --mount=type=bind,from=build,source=/root/rpmbuild/rpm,target=/rpm \
    --mount=type=bind,from=build,source=/root/rpmbuild/RPMS,target=/accel-rpms \
    --mount=type=cache,target=/var/cache/dnf \
    --mount=type=cache,target=/var/lib/dnf \
    set -eux; \
    \
    subscription-manager register \
        --activationkey=$(cat /run/secrets/activation-key) \
        --org=$(cat /run/secrets/org-id); \
    \
    subscription-manager repos \
        --enable=rhel-10-for-x86_64-baseos-rpms \
        --enable=rhel-10-for-x86_64-appstream-rpms \
        --enable=codeready-builder-for-rhel-10-x86_64-rpms; \
    \
    dnf $DNF_OPTS install -y \
        dnf-plugins-core \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm; \
    \
    dnf $DNF_OPTS install -y \
        /accel-rpms/$(uname -m)/accel-config-libs-[0-9]*.rpm \
        /accel-rpms/$(uname -m)/accel-config-[0-9]*.rpm; \
    \
    dnf $DNF_OPTS install -y /rpm/$(uname -m)/*.rpm; \
    \
    dnf $DNF_OPTS update -y; \
    \
    subscription-manager unregister

ENTRYPOINT ["/usr/local/bin/nvmf_tgt"]
CMD ["-u", "-r", "/var/tmp/spdk.sock"]
#------------------------------------------------------------------------------
FROM spdk AS bdevperf

ENV BDEVPERF_TEST_DURATION="90" \
    BDEVPERF_SOCKET="/tmp/bdevperf.sock" \
    BDEVPERF_IO_QUEUE="128" \
    BDEVPERF_IO_BS="4096" \
    BDEVPERF_IO_TYPE="verify" \
    BDEVPERF_CORE_LIST="0"

COPY --from=build /src/build/examples/bdevperf /usr/local/bin/bdevperf
COPY --from=build /src/examples/bdev/bdevperf/bdevperf.py /usr/libexec/spdk/scripts/bdevperf.py

RUN echo "#!/bin/sh -x"                                                 > /entrypoint
RUN echo "bdevperf -z -r \$BDEVPERF_SOCKET \\"                         >> /entrypoint
RUN echo "         --lcores \$BDEVPERF_CORE_LIST \\"                   >> /entrypoint
RUN echo "         -q \$BDEVPERF_IO_QUEUE -o \$BDEVPERF_IO_BS \\"      >> /entrypoint
RUN echo "         -w \$BDEVPERF_IO_TYPE -t \$BDEVPERF_TEST_DURATION"  >> /entrypoint

RUN chmod 755 /entrypoint

ENTRYPOINT [ "/entrypoint" ]
